title: "The Technical Communication of Video Games"
description: "ENC 6931 · Topics in Technical Communication · Fall 2026 · University of Central Florida"
baseurl: "/TCandGames"
url: "https://ekjphd.github.io"

defaults:
  - scope:
      path: ""
    values:
      layout: default
